name: CI

on: # yamllint disable-line
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install black
      run: pip install black
    - name: Run black
      run: black --check .

  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install flake8
      run: pip install flake8 flake8-black
    - name: Run flake8
      run: flake8 .

  mypy-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install mypy
      run: pip install mypy
    - name: Run mypy
      run: mypy . --install-types --non-interactive --ignore-missing-imports

  radon-cc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install radon
      run: pip install radon
    - name: Run radon cc
      run: |
        radon cc .
        radon cc . -j | grep -Eq "\"rank\": \"(C|D|F)\"" && exit 1 || exit 0

  radon-mi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install radon
      run: pip install radon
    - name: Run radon mi
      run: |
        radon mi .
        radon mi . -j | grep -Eq "\"rank\": \"(B|C|D|F)\"" && exit 1 || exit 0

  pydocstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install pydocstyle
      run: pip install pydocstyle
    - name: Run pydocstyle
      run: pydocstyle .

  yamllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install yamllint
      run: pip install yamllint
    - name: Run yamllint
      run: yamllint .

  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download hadolint
      # yamllint disable rule:line-length
      run: |
        wget \
          --quiet \
          --output-document=./hadolint \
          https://github.com/hadolint/hadolint/releases/download/v2.14.0/hadolint-Linux-x86_64
        chmod +x ./hadolint
      # yamllint enable rule:line-length
    - name: Run hadolint
      run: ./hadolint Dockerfile

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install -E shell
    - name: Run pytest
      run: |
        poetry run py.test \
          -verbose \
          --cov-report term-missing \
          --cov-report xml \
          --cov=. .
